import re

with open('backend/main.py', 'r', encoding='utf-8') as f:
    text = f.read()

# Add PlaylistRequest to the models at the top
if 'class PlaylistRequest(BaseModel):' not in text:
    old_req = 'class RecommendationRequest(BaseModel):\n    user_id: str'
    new_req = '''class RecommendationRequest(BaseModel):
    user_id: str

class PlaylistRequest(BaseModel):
    user_id: str
    name: str
    track_uris: list[str] = []'''
    text = text.replace(old_req, new_req)

# Add the playlist endpoint at the end of the recommendations section
if '@app.post("/recommendations/playlist")' not in text:
    endpoint = '''
@app.post("/recommendations/playlist")
def create_playlist(payload: PlaylistRequest):
    conn = get_spotify_connection(payload.user_id)
    if not conn or not conn.get("access_token"):
        return {"success": False, "export": True, "error": "No Spotify token"}
    
    # Refresh token if expired
    if spotify_oauth.token_expired(conn):
        new_tokens = spotify_oauth.refresh_access_token(conn["refresh_token"])
        if "access_token" in new_tokens:
            conn["access_token"] = new_tokens["access_token"]
            save_spotify_connection(payload.user_id, conn["spotify_user_id"], conn["access_token"], conn.get("refresh_token"), new_tokens.get("expires_in", 3600))
    
    token = conn["access_token"]
    user_spotify_id = conn["spotify_user_id"]
    
    try:
        # 1. Create playlist
        res = spotify_oauth._post(
            token,
            f"users/{user_spotify_id}/playlists",
            json_data={"name": payload.name, "public": False, "description": "Generated by SonicDNA"}
        )
        if "id" in res:
            playlist_id = res["id"]
            playlist_url = res["external_urls"]["spotify"]
            
            # 2. Add tracks if provided
            if payload.track_uris:
                spotify_oauth._post(
                    token,
                    f"playlists/{playlist_id}/tracks",
                    json_data={"uris": payload.track_uris}
                )
            
            return {"success": True, "playlist_id": playlist_id, "playlist_url": playlist_url}
        return {"success": False, "error": "Failed to create playlist"}
    except Exception as e:
        print(f"[playlist] Error: {e}")
        return {"success": False, "export": True, "error": str(e)}
'''
    text = text + endpoint

with open('backend/main.py', 'w', encoding='utf-8') as f:
    f.write(text)
